# Generated by Django 4.2 on 2023-04-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='clients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controller',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.server'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='controller',
            name='werehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.werehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='werehouse',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.client'),
        ),
        migrations.AddField(
            model_name='werehouse',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.server'),
        ),
    ]
